import { Random } from "../../math/random.js";

export const ManiasCollection = Object.freeze({
    manias: [
        { name: "Ablutomania", description: "Compulsion to wash oneself." },
        { name: "Abulomania", description: "Pathological indecision." },
        { name: "Acluomania", description: "Excessive fondness for darkness." },
        { name: "Acromania", description: "Compulsion for high places." },
        { name: "Agatomania", description: "Pathological kindness." },
        { name: "Agromania", description: "Intense desire to be in open spaces." },
        { name: "Aichmomania", description: "Obsession with sharp or pointed objects." },
        { name: "Algomania", description: "Obsession with pain." },
        { name: "Alliomania", description: "Obsession with garlic." },
        { name: "Amaxomania", description: "Obsession with being in vehicles." },
        { name: "Amenomania", description: "Irrational joy." },
        { name: "Antomania", description: "Obsession with flowers." },
        { name: "Aritmomania", description: "Obsessive concern with numbers." },
        { name: "Asoticamania", description: "Impulsive or reckless spending." },
        { name: "Automania", description: "Excessive fondness for solitude." },
        { name: "Baletomania", description: "Abnormal affection for ballet." },
        { name: "Bibliocleptomania", description: "Compulsion to steal books." },
        { name: "Bibliomania", description: "Obsession with books and/or reading." },
        { name: "Bruxomania", description: "Compulsion to grind teeth." },
        { name: "Cacodemomania", description: "Pathological belief of being possessed by an evil spirit." },
        { name: "Calomania", description: "Obsession with one's own beauty." },
        { name: "Cartacoethes", description: "Uncontrollable compulsion to see maps everywhere." },
        { name: "Catapedamania", description: "Obsession with jumping from high places." },
        { name: "Cheimatomania", description: "Abnormal desire for cold and/or icy things." },
        { name: "Clazomania", description: "Irrational compulsion to shout." },
        { name: "Cleptomania", description: "Irrational compulsion to steal." },
        { name: "Clinomania", description: "Excessive desire to stay in bed." },
        { name: "Coimetromania", description: "Obsession with cemeteries." },
        { name: "Coloromania", description: "Obsession with a specific color." },
        { name: "Coreomania", description: "Mania for dancing or uncontrollable frenzy." },
        { name: "Coulromania", description: "Obsession with clowns." },
        { name: "Countermania", description: "Compulsion to confront fearful situations." },
        { name: "Dacnomania", description: "Obsession with killing." },
        { name: "Demonomania", description: "Pathological belief of being possessed by demons." },
        { name: "Dermatilomania", description: "Compulsion to pick, scratch, or touch one's own or others' skin." },
        { name: "Dikemania", description: "Obsession with seeing justice being done." },
        { name: "Dipsomania", description: "Abnormal desire for alcohol." },
        { name: "Doramania", description: "Obsession with owning animal skins." },
        { name: "Doromania", description: "Obsession with giving gifts." },
        { name: "Drapetomania", description: "Compulsion to flee." },
        { name: "Ecdemomania", description: "Compulsion to wander." },
        { name: "Egomania", description: "Irrational self-centered or self-worshipping attitude." },
        { name: "Eluromania", description: "Abnormal affection for cats." },
        { name: "Empleomania", description: "Insatiable desire to hold a public office." },
        { name: "Enosimania", description: "Pathological belief that someone has sinned." },
        { name: "Epistemomania", description: "Obsession with acquiring knowledge." },
        { name: "Eremiomania", description: "Compulsion for quietness." },
        { name: "Eteromania", description: "Desire for ether." },
        { name: "Fantasmomania", description: "Obsession with ghosts." },
        { name: "Fonomania", description: "Pathological tendency to commit murder." },
        { name: "Fotomania", description: "Pathological desire for light." },
        { name: "Gamomania", description: "Obsession with strange marriage proposals." },
        { name: "Geliomania", description: "Uncontrollable compulsion to laugh." },
        { name: "Gimnomania", description: "Compulsion for nudity." },
        { name: "Goetomania", description: "Obsession with witches and witchcraft." },
        { name: "Grafomania", description: "Obsession with writing or taking notes." },
        { name: "Habromania", description: "Abnormal tendency to create pleasant delusions (despite reality)." },
        { name: "Helmintomania", description: "Intense fascination with worms." },
        { name: "Hidromania", description: "Irrational desire for water." },
        { name: "Hoplomania", description: "Obsession with firearms." },
        { name: "Iconomania", description: "Obsession with icons or portraits." },
        { name: "Ictiomania", description: "Obsession with fish." },
        { name: "Idolomania", description: "Obsession or devotion to an idol." },
        { name: "Infomania", description: "Excessive devotion to accumulating facts." },
        { name: "Ligiromania", description: "Uncontrollable compulsion to make loud or strident noises." },
        { name: "Linonomania", description: "Obsession with ropes or cords." },
        { name: "Lipemania", description: "Abnormal tendency toward deep melancholy." },
        { name: "Loterimania", description: "Extreme desire to participate in lotteries." },
        { name: "Question-Asking Mania", description: "Compulsive desire to ask questions." },
        { name: "Megalitomania", description: "Abnormal tendency to compose strange ideas when in the presence of circles." },
        { name: "Melomania", description: "Obsession with music or a specific melody." },
        { name: "Metromania", description: "Insatiable desire to write verses." },
        { name: "Misomania", description: "Hatred of everything, obsession with hating a subject or group." },
        { name: "Mitomania", description: "Lying or exaggerating in abnormal amounts." },
        { name: "Monomania", description: "Abnormal obsession with a single thought or idea." },
        { name: "Nosomania", description: "Delusions of suffering from an imagined illness." },
        { name: "Notomania", description: "Compulsion to record everything (e.g., with photographs)." },
        { name: "Onicotilomania", description: "Compulsion to pick, bite, or tear nails." },
        { name: "Onomamania", description: "Obsession with names (people, places, things)." },
        { name: "Onomatomania", description: "Irresistible desire to repeat certain words." },
        { name: "Opsomania", description: "Abnormal fondness for a certain type of food." },
        { name: "Paramania", description: "Abnormal pleasure in complaining." },
        { name: "Personamania", description: "Compulsion to wear masks." },
        { name: "Piromania", description: "Compulsion to start fires." },
        { name: "Planomania", description: "Abnormal desire to disobey social norms." },
        { name: "Plutomania", description: "Obsessive desire for wealth." },
        { name: "Pseudomania", description: "Irrational compulsion to lie." },
        { name: "Doodling Mania", description: "Obsession with doodling/drawing to keep hands busy." },
        { name: "Rinotilexomania", description: "Compulsive desire to pick the nose or clean the nose with the finger." },
        { name: "Siderodromomania", description: "Intense fascination with trains and railway travel." },
        { name: "Sophomania", description: "The illusion of being incredibly intelligent." },
        { name: "Tanatomania", description: "Belief that someone is cursed by death magic." },
        { name: "Technomania", description: "Obsession with new technologies." },
        { name: "Teomania", description: "Belief that one is a god." },
        { name: "Tiflomania", description: "Pathological blindness." },
        { name: "Titilomania", description: "Compulsion to scratch oneself." },
        { name: "Tomomania", description: "Irrational preference for undergoing surgeries or operations." },
        { name: "Trichotillomania", description: "Desire to pull out one's own hair." },
        { name: "Xenomania", description: "Obsession with foreign things." },
        { name: "Zoomania", description: "Insane fondness for animals." }
    ],

    getRandomMania: function () {
        return Random.getRandomArrayElement(this.manias);
    },
});