import { Random } from "../../math/random.js";

export const OccupationsCollection = Object.freeze({
    occupations: [
        "Lawyer",
        "Wanderer",
        "Antique Dealer",
        "Artist",
        "Athlete",
        "Author",
        "Librarian",
        "Clergy, Church Member",
        "Criminal",
        "Private Detective",
        "Dilettante",
        "Engineer",
        "Enthusiast",
        "Farmer",
        "Hacker",
        "Police Investigator",
        "Journalist",
        "Doctor",
        "Tribe Member",
        "Missionary",
        "Musician",
        "Police Officer",
        "Military Officer",
        "Parapsychologist",
        "Pilot",
        "Professor",
        "Entertainment Professional",
        "Soldier",
        "Architect",
        "Astronomer",
        "Science Fiction Author",
        "Biologist",
        "Computer Scientist",
        "IT Consultant",
        "Graphic Designer",
        "Game Developer",
        "Economist",
        "Video Editor",
        "Entrepreneur",
        "Nurse",
        "Technical Writer",
        "Pharmacist",
        "Photographer",
        "Geologist",
        "Project Manager",
        "Illustrator",
        "Interpreter",
        "Judge",
        "Mathematician",
        "Nutritionist",
        "Paleontologist",
        "Researcher",
        "Test Pilot",
        "Programmer",
        "Psychologist",
        "Chemist",
        "Advertising Copywriter",
        "Occupational Therapist",
        "Translator",
        "Urban Planner",
        "Veterinarian",
        "Business Administrator",
        "Data Analyst",
        "Archivist",
        "Social Worker",
        "Call Center Operator",
        "Firefighter",
        "Bank Teller",
        "Chef",
        "Financial Consultant",
        "Real Estate Broker",
        "Seamstress",
        "Dentist",
        "Fashion Designer",
        "Electrician",
        "Plumber",
        "Creative Writer",
        "Blacksmith",
        "Wedding Photographer",
        "Waiter",
        "Forest Ranger",
        "Tour Guide",
        "Fitness Instructor",
        "Car Washer",
        "Massage Therapist",
        "Bus Driver",
        "Machine Operator",
        "Baker",
        "Mason",
        "Painter",
        "Receptionist",
        "Public Relations",
        "Reporter",
        "Lifeguard",
        "Secretary",
        "Security Guard",
        "Holistic Therapist",
        "Treasurer",
        "Laboratory Technician",
        "IT Technician",
        "Radiology Technician",
        "Surveyor",
        "Salesperson",
        "Glazier",
        "Web Designer",
        "Caretaker",
        "Acupuncturist",
        "Travel Agent",
        "HR Analyst",
        "Landscape Architect",
        "Marketing Assistant",
        "Astrologer",
        "Barista",
        "Biochemist",
        "Cartoonist",
        "Grill Chef",
        "Coach",
        "Flight Attendant",
        "School Counselor",
        "Event Coordinator",
        "Butcher",
        "Museum Curator",
        "Interior Designer",
        "Industrial Designer",
        "Criminal Detective",
        "Book Editor",
        "Automotive Electrician",
        "Esthetician",
        "Physiotherapist",
        "Forensic Photographer",
        "HR Manager",
        "Historian",
        "Comedian",
        "Dance Instructor",
        "Gardener",
        "Jeweler",
        "Community Leader",
        "Makeup Artist",
        "Sailor",
        "Financial Mathematician",
        "Maitre",
        "Metallurgist",
        "Delivery Driver",
        "Crane Operator",
        "Event Organizer",
        "Motivational Speaker",
        "Commercial Pilot",
        "TV Producer",
        "E-Sports Professional",
        "Radiologist",
        "Appliance Repairer",
        "Sports Reporter",
        "Scrum Master",
        "Sommelier",
        "Maintenance Supervisor",
        "Taxi Driver",
        "Couples Therapist",
        "Treasurer",
        "Automation Technician",
        "Occupational Safety Technician",
        "Sound Technician",
        "Tourism Technician",
        "Optics Technician",
        "Veterinary Technician",
        "Occupational Therapist",
        "Surveyor",
        "Trader",
        "Animal Trainer",
        "Wildlife Veterinarian",
        "Zootechnics",
    ],

    getRandomOccupation: function () {
        return Random.getRandomArrayElement(this.occupations);
    },
});